"""Make cat id required on slideshows

Revision ID: 791b5de9a19f
Revises: 6d90ae4cfe49
Create Date: 2025-10-19 11:25:59.838910

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '791b5de9a19f'
down_revision = '6d90ae4cfe49'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('slideshow', 'cat_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('slideshow', 'cat_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
